[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
argh = "0.1.12"
solana-rpc-client = "1.17.16"
solana-sdk = "1.17.16"
borsh = "0.10.3"
sha256 = "1.5.0"


